server:
  port: 8064

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: efexunn
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect