server:
  port: 8080

auth:
  service:
    url: http://localhost:8064

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: demo-service
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=0
            - JwtValidation
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=0