server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications
      username: efexunn
      password: efe123
      authentication-database: admin

  mail:
    host: localhost
    port: 1025
    username: efe@mail.com
    password: efe123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: false
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
    default-encoding: UTF-8

