services:
  postgres:
    container_name: microservice-postgres
    image: postgres
    environment:
      POSTGRES_USER: efexunn
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservice-net
    restart: unless-stopped

networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
