services:
  postgres:
    container_name: microservice-postgres
    image: postgres
    environment:
      POSTGRES_USER: efexunn
      POSTGRES_PASSWORD: efe123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservice-net
    restart: unless-stopped

  mail-dev:
    container_name: microservice-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
